name: Build SLN

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install Vulkan SDK
        shell: pwsh
        run: |
          $version = "1.4.335.0"
          $url = "https://sdk.lunarg.com/sdk/download/$version/windows/vulkansdk-windows-X64-$version.exe"
          $installer = "$env:RUNNER_TEMP\vulkansdk-windows-X64-$version.exe"

          Invoke-WebRequest -Uri $url -OutFile $installer

          Start-Process -FilePath $installer `
            -ArgumentList "--root C:\VulkanSDK\$version --accept-licenses --default-answer --confirm-command install" `
            -Wait

          echo "VULKAN_SDK=C:\VulkanSDK\$version" >> $env:GITHUB_ENV
          echo "C:\VulkanSDK\$version\Bin" >> $env:GITHUB_PATH

      - name: Check Vulkan SDK
        shell: pwsh
        run: |
          echo "VULKAN_SDK=$env:VULKAN_SDK"
          glslc --version
          glslangValidator --version

      - name: Build solution
        run: msbuild vulkan-c-learning.sln /p:Configuration=Debug /p:Platform=x64
        